//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsendexApi.Soap.SendService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="com.esendex.ems.soapinterface", ConfigurationName="Soap.SendService.SendServiceSoap")]
    public interface SendServiceSoap {
        
        // CODEGEN: Generating message contract since message SendMessageRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/SendMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EsendexApi.Soap.SendService.SendMessageResponse SendMessage(EsendexApi.Soap.SendService.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/SendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<EsendexApi.Soap.SendService.SendMessageResponse> SendMessageAsync(EsendexApi.Soap.SendService.SendMessageRequest request);
        
        // CODEGEN: Generating message contract since message SendMessageFullRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/SendMessageFull", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EsendexApi.Soap.SendService.SendMessageFullResponse SendMessageFull(EsendexApi.Soap.SendService.SendMessageFullRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/SendMessageFull", ReplyAction="*")]
        System.Threading.Tasks.Task<EsendexApi.Soap.SendService.SendMessageFullResponse> SendMessageFullAsync(EsendexApi.Soap.SendService.SendMessageFullRequest request);
        
        // CODEGEN: Generating message contract since message SendMessageMultipleRecipientsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/SendMessageMultipleRecipients", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EsendexApi.Soap.SendService.SendMessageMultipleRecipientsResponse SendMessageMultipleRecipients(EsendexApi.Soap.SendService.SendMessageMultipleRecipientsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/SendMessageMultipleRecipients", ReplyAction="*")]
        System.Threading.Tasks.Task<EsendexApi.Soap.SendService.SendMessageMultipleRecipientsResponse> SendMessageMultipleRecipientsAsync(EsendexApi.Soap.SendService.SendMessageMultipleRecipientsRequest request);
        
        // CODEGEN: Generating message contract since message SendMessageMultipleRecipientsFullRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/SendMessageMultipleRecipientsFull", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EsendexApi.Soap.SendService.SendMessageMultipleRecipientsFullResponse SendMessageMultipleRecipientsFull(EsendexApi.Soap.SendService.SendMessageMultipleRecipientsFullRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/SendMessageMultipleRecipientsFull", ReplyAction="*")]
        System.Threading.Tasks.Task<EsendexApi.Soap.SendService.SendMessageMultipleRecipientsFullResponse> SendMessageMultipleRecipientsFullAsync(EsendexApi.Soap.SendService.SendMessageMultipleRecipientsFullRequest request);
        
        // CODEGEN: Generating message contract since message SendMessageBatchRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/SendMessageBatch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EsendexApi.Soap.SendService.SendMessageBatchResponse SendMessageBatch(EsendexApi.Soap.SendService.SendMessageBatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/SendMessageBatch", ReplyAction="*")]
        System.Threading.Tasks.Task<EsendexApi.Soap.SendService.SendMessageBatchResponse> SendMessageBatchAsync(EsendexApi.Soap.SendService.SendMessageBatchRequest request);
        
        // CODEGEN: Generating message contract since message GetMessageStatusRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/GetMessageStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EsendexApi.Soap.SendService.GetMessageStatusResponse GetMessageStatus(EsendexApi.Soap.SendService.GetMessageStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/GetMessageStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<EsendexApi.Soap.SendService.GetMessageStatusResponse> GetMessageStatusAsync(EsendexApi.Soap.SendService.GetMessageStatusRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.esendex.ems.soapinterface")]
    public partial class MessengerHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string accountField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("Account");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.esendex.ems.soapinterface")]
    public partial class messagesubmission : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string originatorField;
        
        private string recipientField;
        
        private string bodyField;
        
        private MessageContentType typeField;
        
        private int validityperiodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string originator {
            get {
                return this.originatorField;
            }
            set {
                this.originatorField = value;
                this.RaisePropertyChanged("originator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
                this.RaisePropertyChanged("recipient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("body");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public MessageContentType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int validityperiod {
            get {
                return this.validityperiodField;
            }
            set {
                this.validityperiodField = value;
                this.RaisePropertyChanged("validityperiod");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.esendex.ems.soapinterface")]
    public enum MessageContentType {
        
        /// <remarks/>
        Text,
        
        /// <remarks/>
        Binary,
        
        /// <remarks/>
        SmartMessage,
        
        /// <remarks/>
        Unicode,
        
        /// <remarks/>
        WapPush,
        
        /// <remarks/>
        LongMessage,
        
        /// <remarks/>
        WDPMessage,
        
        /// <remarks/>
        AdvancedMessage,
        
        /// <remarks/>
        VoiceMessage,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.esendex.ems.soapinterface")]
    public enum MessageType {
        
        /// <remarks/>
        Text,
        
        /// <remarks/>
        Binary,
        
        /// <remarks/>
        SmartMessage,
        
        /// <remarks/>
        Unicode,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessage", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="com.esendex.ems.soapinterface")]
        public EsendexApi.Soap.SendService.MessengerHeader MessengerHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public string recipient;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=1)]
        public string body;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=2)]
        public EsendexApi.Soap.SendService.MessageType type;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(EsendexApi.Soap.SendService.MessengerHeader MessengerHeader, string recipient, string body, EsendexApi.Soap.SendService.MessageType type) {
            this.MessengerHeader = MessengerHeader;
            this.recipient = recipient;
            this.body = body;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageResponse", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public string SendMessageResult;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(string SendMessageResult) {
            this.SendMessageResult = SendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageFull", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class SendMessageFullRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="com.esendex.ems.soapinterface")]
        public EsendexApi.Soap.SendService.MessengerHeader MessengerHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public string originator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=1)]
        public string recipient;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=2)]
        public string body;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=3)]
        public EsendexApi.Soap.SendService.MessageType type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=4)]
        public int validityperiod;
        
        public SendMessageFullRequest() {
        }
        
        public SendMessageFullRequest(EsendexApi.Soap.SendService.MessengerHeader MessengerHeader, string originator, string recipient, string body, EsendexApi.Soap.SendService.MessageType type, int validityperiod) {
            this.MessengerHeader = MessengerHeader;
            this.originator = originator;
            this.recipient = recipient;
            this.body = body;
            this.type = type;
            this.validityperiod = validityperiod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageFullResponse", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class SendMessageFullResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public string SendMessageFullResult;
        
        public SendMessageFullResponse() {
        }
        
        public SendMessageFullResponse(string SendMessageFullResult) {
            this.SendMessageFullResult = SendMessageFullResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageMultipleRecipients", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class SendMessageMultipleRecipientsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="com.esendex.ems.soapinterface")]
        public EsendexApi.Soap.SendService.MessengerHeader MessengerHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public string[] recipients;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=1)]
        public string body;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=2)]
        public EsendexApi.Soap.SendService.MessageType type;
        
        public SendMessageMultipleRecipientsRequest() {
        }
        
        public SendMessageMultipleRecipientsRequest(EsendexApi.Soap.SendService.MessengerHeader MessengerHeader, string[] recipients, string body, EsendexApi.Soap.SendService.MessageType type) {
            this.MessengerHeader = MessengerHeader;
            this.recipients = recipients;
            this.body = body;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageMultipleRecipientsResponse", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class SendMessageMultipleRecipientsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public string[] SendMessageMultipleRecipientsResult;
        
        public SendMessageMultipleRecipientsResponse() {
        }
        
        public SendMessageMultipleRecipientsResponse(string[] SendMessageMultipleRecipientsResult) {
            this.SendMessageMultipleRecipientsResult = SendMessageMultipleRecipientsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageMultipleRecipientsFull", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class SendMessageMultipleRecipientsFullRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="com.esendex.ems.soapinterface")]
        public EsendexApi.Soap.SendService.MessengerHeader MessengerHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public string originator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=1)]
        public string[] recipients;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=2)]
        public string body;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=3)]
        public EsendexApi.Soap.SendService.MessageType type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=4)]
        public int validityperiod;
        
        public SendMessageMultipleRecipientsFullRequest() {
        }
        
        public SendMessageMultipleRecipientsFullRequest(EsendexApi.Soap.SendService.MessengerHeader MessengerHeader, string originator, string[] recipients, string body, EsendexApi.Soap.SendService.MessageType type, int validityperiod) {
            this.MessengerHeader = MessengerHeader;
            this.originator = originator;
            this.recipients = recipients;
            this.body = body;
            this.type = type;
            this.validityperiod = validityperiod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageMultipleRecipientsFullResponse", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class SendMessageMultipleRecipientsFullResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public string[] SendMessageMultipleRecipientsFullResult;
        
        public SendMessageMultipleRecipientsFullResponse() {
        }
        
        public SendMessageMultipleRecipientsFullResponse(string[] SendMessageMultipleRecipientsFullResult) {
            this.SendMessageMultipleRecipientsFullResult = SendMessageMultipleRecipientsFullResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageBatch", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class SendMessageBatchRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="com.esendex.ems.soapinterface")]
        public EsendexApi.Soap.SendService.MessengerHeader MessengerHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public EsendexApi.Soap.SendService.messagesubmission[] messages;
        
        public SendMessageBatchRequest() {
        }
        
        public SendMessageBatchRequest(EsendexApi.Soap.SendService.MessengerHeader MessengerHeader, EsendexApi.Soap.SendService.messagesubmission[] messages) {
            this.MessengerHeader = MessengerHeader;
            this.messages = messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageBatchResponse", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class SendMessageBatchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public string[] SendMessageBatchResult;
        
        public SendMessageBatchResponse() {
        }
        
        public SendMessageBatchResponse(string[] SendMessageBatchResult) {
            this.SendMessageBatchResult = SendMessageBatchResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.esendex.ems.soapinterface")]
    public enum MessageStatusCode {
        
        /// <remarks/>
        Queued,
        
        /// <remarks/>
        Sent,
        
        /// <remarks/>
        Delivered,
        
        /// <remarks/>
        Failed,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageStatus", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class GetMessageStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="com.esendex.ems.soapinterface")]
        public EsendexApi.Soap.SendService.MessengerHeader MessengerHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public string id;
        
        public GetMessageStatusRequest() {
        }
        
        public GetMessageStatusRequest(EsendexApi.Soap.SendService.MessengerHeader MessengerHeader, string id) {
            this.MessengerHeader = MessengerHeader;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageStatusResponse", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class GetMessageStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public EsendexApi.Soap.SendService.MessageStatusCode GetMessageStatusResult;
        
        public GetMessageStatusResponse() {
        }
        
        public GetMessageStatusResponse(EsendexApi.Soap.SendService.MessageStatusCode GetMessageStatusResult) {
            this.GetMessageStatusResult = GetMessageStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendServiceSoapChannel : EsendexApi.Soap.SendService.SendServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendServiceSoapClient : System.ServiceModel.ClientBase<EsendexApi.Soap.SendService.SendServiceSoap>, EsendexApi.Soap.SendService.SendServiceSoap {
        
        public SendServiceSoapClient() {
        }
        
        public SendServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EsendexApi.Soap.SendService.SendMessageResponse EsendexApi.Soap.SendService.SendServiceSoap.SendMessage(EsendexApi.Soap.SendService.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public string SendMessage(EsendexApi.Soap.SendService.MessengerHeader MessengerHeader, string recipient, string body, EsendexApi.Soap.SendService.MessageType type) {
            EsendexApi.Soap.SendService.SendMessageRequest inValue = new EsendexApi.Soap.SendService.SendMessageRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.recipient = recipient;
            inValue.body = body;
            inValue.type = type;
            EsendexApi.Soap.SendService.SendMessageResponse retVal = ((EsendexApi.Soap.SendService.SendServiceSoap)(this)).SendMessage(inValue);
            return retVal.SendMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EsendexApi.Soap.SendService.SendMessageResponse> EsendexApi.Soap.SendService.SendServiceSoap.SendMessageAsync(EsendexApi.Soap.SendService.SendMessageRequest request) {
            return base.Channel.SendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<EsendexApi.Soap.SendService.SendMessageResponse> SendMessageAsync(EsendexApi.Soap.SendService.MessengerHeader MessengerHeader, string recipient, string body, EsendexApi.Soap.SendService.MessageType type) {
            EsendexApi.Soap.SendService.SendMessageRequest inValue = new EsendexApi.Soap.SendService.SendMessageRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.recipient = recipient;
            inValue.body = body;
            inValue.type = type;
            return ((EsendexApi.Soap.SendService.SendServiceSoap)(this)).SendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EsendexApi.Soap.SendService.SendMessageFullResponse EsendexApi.Soap.SendService.SendServiceSoap.SendMessageFull(EsendexApi.Soap.SendService.SendMessageFullRequest request) {
            return base.Channel.SendMessageFull(request);
        }
        
        public string SendMessageFull(EsendexApi.Soap.SendService.MessengerHeader MessengerHeader, string originator, string recipient, string body, EsendexApi.Soap.SendService.MessageType type, int validityperiod) {
            EsendexApi.Soap.SendService.SendMessageFullRequest inValue = new EsendexApi.Soap.SendService.SendMessageFullRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.originator = originator;
            inValue.recipient = recipient;
            inValue.body = body;
            inValue.type = type;
            inValue.validityperiod = validityperiod;
            EsendexApi.Soap.SendService.SendMessageFullResponse retVal = ((EsendexApi.Soap.SendService.SendServiceSoap)(this)).SendMessageFull(inValue);
            return retVal.SendMessageFullResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EsendexApi.Soap.SendService.SendMessageFullResponse> EsendexApi.Soap.SendService.SendServiceSoap.SendMessageFullAsync(EsendexApi.Soap.SendService.SendMessageFullRequest request) {
            return base.Channel.SendMessageFullAsync(request);
        }
        
        public System.Threading.Tasks.Task<EsendexApi.Soap.SendService.SendMessageFullResponse> SendMessageFullAsync(EsendexApi.Soap.SendService.MessengerHeader MessengerHeader, string originator, string recipient, string body, EsendexApi.Soap.SendService.MessageType type, int validityperiod) {
            EsendexApi.Soap.SendService.SendMessageFullRequest inValue = new EsendexApi.Soap.SendService.SendMessageFullRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.originator = originator;
            inValue.recipient = recipient;
            inValue.body = body;
            inValue.type = type;
            inValue.validityperiod = validityperiod;
            return ((EsendexApi.Soap.SendService.SendServiceSoap)(this)).SendMessageFullAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EsendexApi.Soap.SendService.SendMessageMultipleRecipientsResponse EsendexApi.Soap.SendService.SendServiceSoap.SendMessageMultipleRecipients(EsendexApi.Soap.SendService.SendMessageMultipleRecipientsRequest request) {
            return base.Channel.SendMessageMultipleRecipients(request);
        }
        
        public string[] SendMessageMultipleRecipients(EsendexApi.Soap.SendService.MessengerHeader MessengerHeader, string[] recipients, string body, EsendexApi.Soap.SendService.MessageType type) {
            EsendexApi.Soap.SendService.SendMessageMultipleRecipientsRequest inValue = new EsendexApi.Soap.SendService.SendMessageMultipleRecipientsRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.recipients = recipients;
            inValue.body = body;
            inValue.type = type;
            EsendexApi.Soap.SendService.SendMessageMultipleRecipientsResponse retVal = ((EsendexApi.Soap.SendService.SendServiceSoap)(this)).SendMessageMultipleRecipients(inValue);
            return retVal.SendMessageMultipleRecipientsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EsendexApi.Soap.SendService.SendMessageMultipleRecipientsResponse> EsendexApi.Soap.SendService.SendServiceSoap.SendMessageMultipleRecipientsAsync(EsendexApi.Soap.SendService.SendMessageMultipleRecipientsRequest request) {
            return base.Channel.SendMessageMultipleRecipientsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EsendexApi.Soap.SendService.SendMessageMultipleRecipientsResponse> SendMessageMultipleRecipientsAsync(EsendexApi.Soap.SendService.MessengerHeader MessengerHeader, string[] recipients, string body, EsendexApi.Soap.SendService.MessageType type) {
            EsendexApi.Soap.SendService.SendMessageMultipleRecipientsRequest inValue = new EsendexApi.Soap.SendService.SendMessageMultipleRecipientsRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.recipients = recipients;
            inValue.body = body;
            inValue.type = type;
            return ((EsendexApi.Soap.SendService.SendServiceSoap)(this)).SendMessageMultipleRecipientsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EsendexApi.Soap.SendService.SendMessageMultipleRecipientsFullResponse EsendexApi.Soap.SendService.SendServiceSoap.SendMessageMultipleRecipientsFull(EsendexApi.Soap.SendService.SendMessageMultipleRecipientsFullRequest request) {
            return base.Channel.SendMessageMultipleRecipientsFull(request);
        }
        
        public string[] SendMessageMultipleRecipientsFull(EsendexApi.Soap.SendService.MessengerHeader MessengerHeader, string originator, string[] recipients, string body, EsendexApi.Soap.SendService.MessageType type, int validityperiod) {
            EsendexApi.Soap.SendService.SendMessageMultipleRecipientsFullRequest inValue = new EsendexApi.Soap.SendService.SendMessageMultipleRecipientsFullRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.originator = originator;
            inValue.recipients = recipients;
            inValue.body = body;
            inValue.type = type;
            inValue.validityperiod = validityperiod;
            EsendexApi.Soap.SendService.SendMessageMultipleRecipientsFullResponse retVal = ((EsendexApi.Soap.SendService.SendServiceSoap)(this)).SendMessageMultipleRecipientsFull(inValue);
            return retVal.SendMessageMultipleRecipientsFullResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EsendexApi.Soap.SendService.SendMessageMultipleRecipientsFullResponse> EsendexApi.Soap.SendService.SendServiceSoap.SendMessageMultipleRecipientsFullAsync(EsendexApi.Soap.SendService.SendMessageMultipleRecipientsFullRequest request) {
            return base.Channel.SendMessageMultipleRecipientsFullAsync(request);
        }
        
        public System.Threading.Tasks.Task<EsendexApi.Soap.SendService.SendMessageMultipleRecipientsFullResponse> SendMessageMultipleRecipientsFullAsync(EsendexApi.Soap.SendService.MessengerHeader MessengerHeader, string originator, string[] recipients, string body, EsendexApi.Soap.SendService.MessageType type, int validityperiod) {
            EsendexApi.Soap.SendService.SendMessageMultipleRecipientsFullRequest inValue = new EsendexApi.Soap.SendService.SendMessageMultipleRecipientsFullRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.originator = originator;
            inValue.recipients = recipients;
            inValue.body = body;
            inValue.type = type;
            inValue.validityperiod = validityperiod;
            return ((EsendexApi.Soap.SendService.SendServiceSoap)(this)).SendMessageMultipleRecipientsFullAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EsendexApi.Soap.SendService.SendMessageBatchResponse EsendexApi.Soap.SendService.SendServiceSoap.SendMessageBatch(EsendexApi.Soap.SendService.SendMessageBatchRequest request) {
            return base.Channel.SendMessageBatch(request);
        }
        
        public string[] SendMessageBatch(EsendexApi.Soap.SendService.MessengerHeader MessengerHeader, EsendexApi.Soap.SendService.messagesubmission[] messages) {
            EsendexApi.Soap.SendService.SendMessageBatchRequest inValue = new EsendexApi.Soap.SendService.SendMessageBatchRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.messages = messages;
            EsendexApi.Soap.SendService.SendMessageBatchResponse retVal = ((EsendexApi.Soap.SendService.SendServiceSoap)(this)).SendMessageBatch(inValue);
            return retVal.SendMessageBatchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EsendexApi.Soap.SendService.SendMessageBatchResponse> EsendexApi.Soap.SendService.SendServiceSoap.SendMessageBatchAsync(EsendexApi.Soap.SendService.SendMessageBatchRequest request) {
            return base.Channel.SendMessageBatchAsync(request);
        }
        
        public System.Threading.Tasks.Task<EsendexApi.Soap.SendService.SendMessageBatchResponse> SendMessageBatchAsync(EsendexApi.Soap.SendService.MessengerHeader MessengerHeader, EsendexApi.Soap.SendService.messagesubmission[] messages) {
            EsendexApi.Soap.SendService.SendMessageBatchRequest inValue = new EsendexApi.Soap.SendService.SendMessageBatchRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.messages = messages;
            return ((EsendexApi.Soap.SendService.SendServiceSoap)(this)).SendMessageBatchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EsendexApi.Soap.SendService.GetMessageStatusResponse EsendexApi.Soap.SendService.SendServiceSoap.GetMessageStatus(EsendexApi.Soap.SendService.GetMessageStatusRequest request) {
            return base.Channel.GetMessageStatus(request);
        }
        
        public EsendexApi.Soap.SendService.MessageStatusCode GetMessageStatus(EsendexApi.Soap.SendService.MessengerHeader MessengerHeader, string id) {
            EsendexApi.Soap.SendService.GetMessageStatusRequest inValue = new EsendexApi.Soap.SendService.GetMessageStatusRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.id = id;
            EsendexApi.Soap.SendService.GetMessageStatusResponse retVal = ((EsendexApi.Soap.SendService.SendServiceSoap)(this)).GetMessageStatus(inValue);
            return retVal.GetMessageStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EsendexApi.Soap.SendService.GetMessageStatusResponse> EsendexApi.Soap.SendService.SendServiceSoap.GetMessageStatusAsync(EsendexApi.Soap.SendService.GetMessageStatusRequest request) {
            return base.Channel.GetMessageStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<EsendexApi.Soap.SendService.GetMessageStatusResponse> GetMessageStatusAsync(EsendexApi.Soap.SendService.MessengerHeader MessengerHeader, string id) {
            EsendexApi.Soap.SendService.GetMessageStatusRequest inValue = new EsendexApi.Soap.SendService.GetMessageStatusRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.id = id;
            return ((EsendexApi.Soap.SendService.SendServiceSoap)(this)).GetMessageStatusAsync(inValue);
        }
    }
}
